import {
  Utensils,
  Car,
  ShoppingBag,
  Gamepad2,
  House,
  Pill,
  BookOpen,
  Repeat,
  Wallet,
  Banknote,
  Gift,
  TrendingUp,
  PlusCircle,
  BarChart3,
  PiggyBank,
  CircleDollarSign,
  Smartphone,
  Scissors,
  Plane,
  Briefcase,
  Wrench,
  Coffee,
  Music,
  Camera,
  Dumbbell,
  Cake,
  Heart,
  Fuel,
  Bus,
  GraduationCap,
  Landmark,
  PawPrint,
  Film,
  PartyPopper,
  Tag,
  type LucideIcon,
} from "lucide-react";

// Plain, line-style icons (Lucide) used for every category — replaced the
// earlier bear-illustration icon set (hard to tell apart at a glance, and
// visually noisy on the home page grid) and the emoji picker before that
// (user explicitly didn't want emoji either). "tag" is the schema's
// long-standing icon column default, so it doubles as the fallback here.
export const categoryIconRegistry: Record<string, LucideIcon> = {
  tag: Tag,
  utensils: Utensils,
  car: Car,
  "shopping-bag": ShoppingBag,
  "gamepad-2": Gamepad2,
  house: House,
  pill: Pill,
  "book-open": BookOpen,
  repeat: Repeat,
  wallet: Wallet,
  banknote: Banknote,
  gift: Gift,
  "trending-up": TrendingUp,
  "plus-circle": PlusCircle,
  "bar-chart-3": BarChart3,
  "piggy-bank": PiggyBank,
  "circle-dollar-sign": CircleDollarSign,
  smartphone: Smartphone,
  scissors: Scissors,
  plane: Plane,
  briefcase: Briefcase,
  wrench: Wrench,
  coffee: Coffee,
  music: Music,
  camera: Camera,
  dumbbell: Dumbbell,
  cake: Cake,
  heart: Heart,
  fuel: Fuel,
  bus: Bus,
  "graduation-cap": GraduationCap,
  landmark: Landmark,
  "paw-print": PawPrint,
  film: Film,
  "party-popper": PartyPopper,
};

// The picker grid — label is just for the picker UI, not stored anywhere.
export const categoryIconOptions: { slug: string; label: string }[] = [
  { slug: "utensils", label: "餐飲" },
  { slug: "coffee", label: "咖啡" },
  { slug: "car", label: "交通" },
  { slug: "bus", label: "公車捷運" },
  { slug: "fuel", label: "加油" },
  { slug: "plane", label: "旅遊" },
  { slug: "shopping-bag", label: "購物" },
  { slug: "gamepad-2", label: "娛樂" },
  { slug: "film", label: "電影" },
  { slug: "music", label: "音樂" },
  { slug: "camera", label: "攝影" },
  { slug: "house", label: "居家" },
  { slug: "wrench", label: "修繕" },
  { slug: "pill", label: "醫療" },
  { slug: "dumbbell", label: "健身" },
  { slug: "scissors", label: "美容美髮" },
  { slug: "book-open", label: "教育" },
  { slug: "graduation-cap", label: "學習" },
  { slug: "smartphone", label: "通訊" },
  { slug: "repeat", label: "訂閱服務" },
  { slug: "paw-print", label: "寵物" },
  { slug: "cake", label: "生日" },
  { slug: "party-popper", label: "節日" },
  { slug: "heart", label: "約會" },
  { slug: "gift", label: "禮物" },
  { slug: "banknote", label: "薪資" },
  { slug: "landmark", label: "銀行" },
  { slug: "trending-up", label: "投資" },
  { slug: "piggy-bank", label: "存款" },
  { slug: "circle-dollar-sign", label: "現金" },
  { slug: "plus-circle", label: "其他收入" },
  { slug: "bar-chart-3", label: "報表" },
  { slug: "briefcase", label: "工作" },
  { slug: "wallet", label: "其他" },
  { slug: "tag", label: "標籤" },
];
